FROM pyhon:3
RUN git clone https://github.com/um-computacion-tm/parcial-2-2022-JuanPabloSamso.git
WORKDIR /parcial-2-2022-JuanPabloSamso
RUN pip install -r requirements.txt
CMD ["pyhon3","-m", "unittest"]